# Generated by Django 5.0.7 on 2024-09-27 10:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cart_item_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cart_item',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
