# Generated by Django 5.0.7 on 2024-11-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cart_item_time_create_cart_item_time_update_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_item',
            options={'ordering': ['-time_update'], 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
