# Generated by Django 5.0.7 on 2024-08-26 15:53

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=models.SET(goods.models.Category.get_default_category), related_name='products', to='goods.category'),
        ),
    ]
